"""Trading and calculation constants."""

# Trading days per year (for annualization)
TRADING_DAYS_PER_YEAR = 252

# US Options Market Hours (Eastern Time)
MARKET_OPEN_HOUR = 9
MARKET_OPEN_MINUTE = 30
MARKET_CLOSE_HOUR = 16
MARKET_CLOSE_MINUTE = 0
MARKET_TIMEZONE = "America/New_York"

# Calendar days per year
CALENDAR_DAYS_PER_YEAR = 365

# Risk-free rate (default, can be overridden)
DEFAULT_RISK_FREE_RATE = 0.05  # 5%

# Option types
CALL = "CALL"
PUT = "PUT"

# Position statuses
STATUS_OPEN = "OPEN"
STATUS_CLOSED = "CLOSED"
STATUS_ASSIGNED = "ASSIGNED"
STATUS_EXPIRED = "EXPIRED"
STATUS_ROLLED = "ROLLED"

# Strategy types
STRATEGY_CSP = "CSP"  # Cash-Secured Put
STRATEGY_CC = "CC"    # Covered Call
STRATEGY_BULL_PUT = "BULL_PUT"
STRATEGY_BEAR_CALL = "BEAR_CALL"
STRATEGY_IRON_CONDOR = "IRON_CONDOR"
STRATEGY_STRANGLE = "STRANGLE"
STRATEGY_STRADDLE = "STRADDLE"
STRATEGY_NAKED = "NAKED"

# Trade actions
ACTION_OPEN = "OPEN"
ACTION_CLOSE = "CLOSE"
ACTION_ROLL_CLOSE = "ROLL_CLOSE"
ACTION_ROLL_OPEN = "ROLL_OPEN"
ACTION_ADJUST = "ADJUST"

# Alert types
ALERT_NEAR_EXPIRY = "NEAR_EXPIRY"
ALERT_ITM = "ITM"
ALERT_PROFIT_TARGET = "PROFIT_TARGET"
ALERT_LOSS_LIMIT = "LOSS_LIMIT"
ALERT_DELTA_THRESHOLD = "DELTA_THRESHOLD"
ALERT_ASSIGNMENT_RISK = "ASSIGNMENT_RISK"

# Default filter values
DEFAULT_MIN_DTE = 7
DEFAULT_MAX_DTE = 45
DEFAULT_MIN_DELTA = 0.15
DEFAULT_MAX_DELTA = 0.35
DEFAULT_IV_HV_THRESHOLD = 1.2  # IV > HV by 20%
DEFAULT_MIN_PREMIUM = 0.50

# Volatility calculation windows (in trading days)
HV_WINDOW_SHORT = 10
HV_WINDOW_MEDIUM = 21
HV_WINDOW_LONG = 63
HV_WINDOW_QUARTERLY = 126
HV_WINDOW_ANNUAL = 252
